Controllers/MailSenderController.cs
using System.Net;
using System.Net.Mail;
using Microsoft.AspNetCore.Mvc;

public class MailSenderController : Controller
{
    public ActionResult Index()
    {
        return View();
    }

    public string SendEmail(string Name, string Email, string Message){
        
        try
        {
            // Credentials
            var credentials = new NetworkCredential("your-email-here@gmail.com", "your-password");

            // Mail message
            var mail = new MailMessage()
            {
                From = new MailAddress("noreply@codinginfinite.com"),
                Subject = "Email Sender App",
                Body = Message
            };

            mail.IsBodyHtml = true;
            mail.To.Add(new MailAddress(Email));

            // Smtp client
            var client = new SmtpClient()
            {
                Port = 587,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Host = "smtp.gmail.com",
                EnableSsl = true,
                Credentials = credentials
            };

            client.Send(mail);

            return "Email Sent Successfully!";
        }
        catch (System.Exception e)
        {
            return e.Message;
        }
        
    }
}

Views/MailSender/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Contact V2</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>

	<div class="bg-contact" style="background-image: url('images/bg-01.jpg');">
		<div class="container-contact">
			<div class="wrap-contact">
				<span class="contact-form-title">
					Contact Us
				</span>

				<div class="wrap-input validate-input" data-validate="Name is required">
					<input class="input" type="text" id="name">
					<span class="focus-input" data-placeholder="NAME"></span>
				</div>

				<div class="wrap-input validate-input" data-validate = "Valid email is required: ex@abc.xyz">
					<input class="input" type="text" id="email">
					<span class="focus-input" data-placeholder="EMAIL"></span>
				</div>

				<div class="wrap-input validate-input" data-validate = "Message is required">
					<textarea class="input" id="message"></textarea>
					<span class="focus-input" data-placeholder="MESSAGE"></span>
				</div>

				<div class="container-contact-form-btn">
					<div class="wrap-contact-form-btn">
						<div class="contact-form-bgbtn"></div>
						<button class="contact-form-btn" onclick="SendEmail()">
							Send Your Message To Us
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>

<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

	<script>

		function SendEmail(){

			$.ajax(
			{
				type: "POST",
				url: '@Url.Action("SendEmail", "MailSender")',
				data: {
					Name: $("#name").val(),
					Email: $("#email").val(),
					Message: $("#message").val()
				},
				error: function (result) {
					console.log(result);
				},
				success: function (result) {
					alert(result);
					$("#name").val("");
					$("#email").val("");
					$("#message").val("");
				}
			});
		}
	</script>

</body>
</html>